---
#
# The variable jws_app_dir must be defined.  Some possible values include
#
# For a RHEL RPM installation
#
#    jws_app_dir: "/opt/rh/jws5/root/usr/share/tomcat/webapps"
#
# For a RHEL zip installation
#
#    jws_app_dir: "/opt/jws-5.5/tomcat/webapps"
#
- name: Deploy a Java war file from a git repository to JBoss Java Web Server
  hosts: "{{ hostlist | default('all') }}"
  become: True
  vars:
    git_app_repo: ""
#    jws_war_name: "HelloServlet-1.0.0.war"
#    git_tmp_checkout_dir: "/var/tmp/checkout"
    git_tmp_checkout_dir: "./mvn_tmp"

    git_commands:
      - git commit -a -m 'Commit from Ansible build'
      - git push

  tasks:

    - name: Ensure that git_app_repo is not null
      assert:
        fail_msg: "The variable git_app_repo must be defined."
        that:
          - git_app_repo != ""

    - name: Ensure that jws_app_dir is not null
      assert:
        fail_msg: "The variable jws_app_dir must be defined."
        that:
          - jws_app_dir != ""

    - name: Ensure git is installed
      yum:
        name: git
        state: present

    - name: Obtain the application
      git:
        repo: "{{ git_app_repo }}"
        dest: "{{ git_tmp_checkout_dir }}"

#    - name: Ensure application is copied
#      command:
#        chdir: "{{ git_tmp_checkout_dir }}"
#        cmd: "cp ./target/{{ jws_war_name }} {{ jws_app_dir }}/{{ dest_war_name }}"
#      ignore_errors: True
#      with_items: "{{ maven_commands }}"

      copy:
        dest: "{{ jws_app_dir }}/{{ dest_war_name }}"
        group: tomcat
        owner: tomcat
        remote_src: Yes
        src: "{{ git_tmp_checkout_dir }}/target/{{ jws_war_name }}"

#    - name: Cleanup temporary directory
#      file:
#        path: "{{ git_tmp_checkout_dir }}"
#        state: absent
