---
#
# The variable jws_app_dir must be defined.  Some possible values include
#
# For a RHEL RPM installation
#
#    jws_app_dir: "/opt/rh/jws5/root/usr/share/tomcat/webapps"
#
# For a RHEL zip installation
#
#    jws_app_dir: "/opt/jws-5.5/tomcat/webapps"
#
- name: Ensure sample JWS application is installed
  hosts: "{{ hostlist | default('all') }}"
  become: True
  vars:
    git_app_repo: "https://github.com/t-prinz/HelloServlet.git"
    jws_war_name: "HelloServlet-1.0.0.war"
    git_tmp_checkout_dir: "/var/tmp/checkout"
    jws_app_dir: ""
    maven_commands:
      - mvn clean
      - mvn package

  tasks:
    - name: Ensure that jws_app_dir is not null
      assert:
        fail_msg: "The variable jws_app_dir must be defined."
        that:
          - jws_app_dir != ""

    - name: Obtain the application
      git:
        repo: "{{ git_app_repo }}"
        dest: "{{ git_tmp_checkout_dir }}"

    - name: Run maven commands
      command:
        chdir: "{{ git_tmp_checkout_dir }}"
        cmd: "{{ item }}"
      ignore_errors: True
      register: maven_output
      with_items: "{{ maven_commands }}"

    - name: Print maven output
      debug:
        var: maven_output
        verbosity: 1

    - name: Ensure application is copied
      copy:
        dest: "{{ jws_app_dir }}"
        group: tomcat
        owner: tomcat
        remote_src: Yes
        src: "{{ git_tmp_checkout_dir }}/target/{{ jws_war_name }}"

    - name: Cleanup temporary directory
      file:
        path: "{{ git_tmp_checkout_dir }}"
        state: absent
