---
- name: Install Java Web Server
  hosts: "{{ vm_fq_hostname | default('NO_HOSTS') }}"
  remote_user: root
  vars:
    git_app_repo: "https://github.com/t-prinz/HelloServlet.git"
    git_tmp_checkout_dir: "/var/tmp/checkout"
    jws_app_dir: "/var/opt/rh/jws5/lib/tomcat/webapps"
    jws_war_name: "HelloServlet-1.0.0.war"

  tasks:
    - name: Obtain the application
      git:
        repo: "{{ git_app_repo }}"
        dest: "{{ git_tmp_checkout_dir }}"

    - name: Ensure application is copied
      copy:
        dest: "{{ jws_app_dir }}"
        group: tomcat
        owner: tomcat
        remote_src: Yes
        src: "{{ git_tmp_checkout_dir }}/target/{{ jws_war_name }}"
#        src: "{{ git_tmp_checkout_dir }}/deployments/{{ jws_war_name }}"

    - name: Cleanup temporary directory
      file:
        path: "{{ git_tmp_checkout_dir }}"
        state: absent
