---
- name: Ensure sample JWS application is installed
  hosts: all
  become: True
  vars:
    git_app_repo: "https://github.com/t-prinz/HelloServlet.git"
    jws_war_name: "HelloServlet-1.0.0.war"
    git_tmp_checkout_dir: "/var/tmp/checkout"
    jws_app_dir: "/opt/rh/jws5/root/usr/share/tomcat/webapps"

  tasks:
    - name: Ensure git is installed
      yum:
        name: git
        state: present

    - name: Obtain the application
      git:
        repo: "{{ git_app_repo }}"
        dest: "{{ git_tmp_checkout_dir }}"

    - name: Ensure application is copied
      copy:
        dest: "{{ jws_app_dir }}"
        group: tomcat
        owner: tomcat
        remote_src: Yes
        src: "{{ git_tmp_checkout_dir }}/target/{{ jws_war_name }}"

    - name: Cleanup temporary directory
      file:
        path: "{{ git_tmp_checkout_dir }}"
        state: absent
