---
- name: Install Java Web Server
  hosts: all
  become: True

  tasks:
    - name: Ensure repositories are enabled
      command: subscription-manager repos --enable=jws-5-for-rhel-7-server-rpms --enable=jb-coreservices-1-for-rhel-7-server-rpms

    - name: Ensure OpenJDK and git are installed
      package:
        name: "{{ item }}"
        state: present
      with_items:
#        - java-1.8.0-openjdk-devel
        - java-11-openjdk-devel
        - git

    - name: Ensure tomcatjss is removed
      package:
        name: tomcatjss
        state: absent

    - name: Ensure JWS is installed
      package:
        name: "@jws5"
        state: present

    - name: Ensure JWS is enabled and started
      service:
        name: jws5-tomcat
        enabled: True
        state: started

#    - name: Open up required firewall port
#      firewalld:
#        immediate: True
#        permanent: True
#        port: "{{ item }}"
#        state: enabled
#      with_items:
#        - "8080/tcp"
