---
- name: Ensure sample JWS applications are installed
  hosts: "{{ hostlist | default('all') }}"
  become: True
  vars:
    jws_instances_vars: ""

  tasks:
    - name: Include JWS instances variables file
      include_vars:
        file: "{{ jws_instances_vars }}"

    - name: Loop over the tasks file that will create each containerized instance
      include_tasks:
        file: files/create_virtualized_app_instances_tasks.yml
      loop: "{{ jws_instances }}"
      loop_control:
        loop_var: outer_item
