---
- name: Ensure Java Web Server (JWS) is installed
  hosts: "{{ hostlist | default('all') }}"
  become: True
  vars:
    configure_firewall: True

  tasks:
    - name: Define repositories to be enabled for RHEL 7
      set_fact:
        rhportal_reg_rhsm_supplemental_repo_list:
          - jws-5-for-rhel-7-server-rpms
          - jb-coreservices-1-for-rhel-7-server-rpms
      when: ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version == "7"

    - name: Define repositories to be enabled for RHEL 8
      set_fact:
        rhportal_reg_rhsm_supplemental_repo_list:
          - jws-5-for-rhel-8-x86_64-rpms
      when: ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version == "8"

    - name: Define repositories to be enabled for RHEL 9
      set_fact:
        rhportal_reg_rhsm_supplemental_repo_list:
          - jws-5-for-rhel-9-x86_64-rpms
      when: ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version == "9"

    - name: Ensure repositories are enabled
      command: "subscription-manager repos --enable={{ item }}"
      with_items: "{{ rhportal_reg_rhsm_supplemental_repo_list }}"

    - name: Ensure firewalld is installed
      package:
        name: firewalld
        state: installed

    - name: Ensure firewalld is enabled and started
      service:
        name: firewalld
        enabled: True
        state: started

    - name: Ensure firewall ports are open
      ansible.posix.firewalld:
        immediate: True
        permanent: True
        port: "{{ item }}"
        state: enabled
      with_items:
        - "8080/tcp"
#        - "8005/tcp"
#        - "8009/tcp"
        - "8443/tcp"
      when: configure_firewall|bool

    - name: Ensure OpenJDK and SSL packages are installed
      package:
        name: "{{ pkgs_to_install }}"
        state: present
      vars:
        pkgs_to_install:
          - java-1.8.0-openjdk-devel
          - openssl
          - apr

    - name: Ensure tomcatjss is removed
      package:
        name: tomcatjss
        state: absent

    - name: Ensure JWS is installed
      package:
        name: "@jws5"
        state: present
      notify: restart_jws

    - name: Ensure JWS is enabled and started
      service:
        name: jws5-tomcat
        enabled: True
        state: started

  handlers:
    - name: restart_jws
      service:
        enabled: True
        name: jws5-tomcat
        state: restarted
