---
- name: Build application with maven and push to git repository
  hosts: "{{ hostlist | default('all') }}"
  vars:
#    git_app_repo: "https://github.com/t-prinz/HelloServlet.git"
    git_app_repo: ""
#    jws_war_name: "HelloServlet-1.0.0.war"
#    git_tmp_checkout_dir: "/var/tmp/checkout"
    git_tmp_checkout_dir: "./mvn_tmp"

    maven_commands:
      - mvn clean
      - mvn package

  tasks:
    - name: Ensure that git_app_repo is not null
      assert:
        fail_msg: "The variable git_app_repo must be defined."
        that:
          - git_app_repo != ""

    - name: Obtain the application
      git:
        repo: "{{ git_app_repo }}"
        dest: "{{ git_tmp_checkout_dir }}"

    - name: Run maven commands
      command:
        chdir: "{{ git_tmp_checkout_dir }}"
        cmd: "{{ item }}"
      ignore_errors: True
      register: maven_output
      with_items: "{{ maven_commands }}"

# Push 

#    - name: Cleanup temporary directory
#      file:
#        path: "{{ git_tmp_checkout_dir }}"
#        state: absent
